=== soyoungkim9/cyberProject/ksy-movie/webapp/coreframe/eclipse/bld-5.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- edited by Sungkwon Kim (CyberImagination, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cyber-i.com/xml/bld"
	targetNamespace="http://www.cyber-i.com/xml/bld">
	<xs:element name="version" default="0.1">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="transaction-type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="" />
				<xs:enumeration value="transction" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="transaction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="info" />
				<xs:element ref="processor-info" />
				<xs:element ref="input" />
				<xs:element ref="output" />
				<xs:element ref="test" minOccurs="0" />
				<xs:element ref="Signature" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="test">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="status" default="developing">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="" />
				<xs:enumeration value="developing" />
				<xs:enumeration value="ready-confirm" />
				<xs:enumeration value="confirmation" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query" />
				<xs:element ref="mapping" />
			</xs:sequence>
			<xs:attribute name="max-rows" type="xs:positiveInteger" use="optional" default="100" />
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="setProperty" type="xs:string" />
	<xs:element name="script" default="//insert Java Code">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="language" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="java" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="import" use="optional" default="java.io.*,java.util.*">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="query">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="" />
								<xs:enumeration value="normal" />
								<xs:enumeration value="batch" />
								<xs:enumeration value="storedprocedure" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="property" >
					<xs:complexType>
						<xs:attribute name="name" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="soap.url" />
									<xs:enumeration value="soap.action" />
									<xs:enumeration value="http.encoding" />
									<xs:enumeration value="http.method" />
									<xs:enumeration value="http.url" />
									<xs:enumeration value="mail.smtp_host" />
									<xs:enumeration value="mail.auth.id" />
									<xs:enumeration value="mail.auth.pwd" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="value" use="required" />
						<xs:attribute name="desc" type="xs:string" />
					</xs:complexType>
				</xs:element>
				
				
	<xs:element name="processor-info">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transaction-type" minOccurs="0" />
				
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded">
					
				</xs:element>
				
				<xs:element ref="cache" minOccurs="0" />
				<xs:element ref="script" minOccurs="0" />
				<xs:element ref="sql" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="dbms" />
						<xs:enumeration value="soap" />
						<xs:enumeration value="http" />
						<xs:enumeration value="java" />
						<xs:enumeration value="mail" />
						<xs:enumeration value="file-reader" />
						<xs:enumeration value="file-writer" />
						<xs:enumeration value="file-reader-binary" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="datasource">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="block" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="setProperty" />
				<xs:element ref="getProperty" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="block" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="xml-document" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="info">
		<xs:complexType>
			<xs:all>
				<xs:element ref="name" minOccurs="0" maxOccurs="1" />
				<xs:element ref="description" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="version" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="author" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="http-access" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="status" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="effective-date" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="http-access" type="xs:boolean" default="false" />
	<xs:element name="getProperty">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:attribute name="value">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="string" />
						<xs:enumeration value="int" />
						<xs:enumeration value="double" />
						<xs:enumeration value="float" />
						<xs:enumeration value="clob" />
						<xs:enumeration value="datetime" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="properties">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xpath">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="default">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="format">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="decimal">
				<xs:simpleType>
					<xs:restriction base="xs:int" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="size" type="xs:positiveInteger" />
			<xs:attribute name="label" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	
	
  <xs:element name="enable" type="xs:string" default="false" />
  <xs:element name="expire" type="xs:positiveInteger" default="60"/>
	<xs:element name="effective-date" type="xs:string" />
	<xs:element name="group" type="xs:string" />
  <xs:element name="max-object-num" type="xs:positiveInteger" default="100"/>
  <xs:element name="event">
    <xs:complexType />
  </xs:element>
  
  
  
	<xs:element name="description" type="xs:string" default="write BLD Description" />
  
  <xs:element name="test-input">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
  
	<xs:element name="case">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="test-input"/>
        
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="cache">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enable"/>
				<xs:element ref="expire" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="max-object-num" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="group" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="event"  minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="block">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="repeat" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xpath" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="ref" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="class" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="xml-document">
		<xs:complexType />
	</xs:element>
	<xs:element name="SignatureValue">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="Signature">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SignatureValue" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== soyoungkim9/cyberProject/coreBoard/webapp/WEB-INF/coreframe/bld/samples/file/getLast.xml
<?xml version="1.0" encoding="EUC-KR"?>
<transaction name="getLast" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<status>confirmation</status>
		<http-access>true</http-access>
		<effective-date></effective-date>
		<description>파일에 기록된 가장 마지막 정보를 추출한다.</description>
		<version>0.1</version>
		<name>최근 주가정보</name>
	</info>

	<processor-info type="file-reader">
		<property desc="" name="fileName" value="test.txt"></property>
		<property name="start-row" value="0"></property>
		<property name="select-rownum" value="1"></property>
		<property name="direction" value="reverse"></property>
		<cache>
			<enable>false</enable>
			<expire></expire>
			<max-object-num></max-object-num>
			<event></event>
		</cache>
		<transaction-type></transaction-type>
	</processor-info>

	<input>
		<block></block>
	</input>

	<output>
		<block name="stock">
			<field label="종목코드" name="jcode" size="6" type="string"></field>
			<field label="종목명" name="hname" size="10" type="string"></field>
			<field label="현재가" name="price" size="10" type="int"></field>
			<field label="고가" name="high" size="10" type="int"></field>
			<field label="저가" name="low" size="10" type="int"></field>
		</block>
	</output>

	<Signature>
		<SignatureValue>d3b9876d26ee7c4987116a710a40747c101</SignatureValue>
	</Signature>
</transaction>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/samples/file/master.xml
<?xml version="1.0" encoding="EUC-KR"?>
<transaction name="master" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<status>confirmation</status>
		<http-access>true</http-access>
		<effective-date></effective-date>
		<description></description>
		<version>0.1</version>
		<name>거래소 마스터 정보</name>
	</info>

	<processor-info type="file-reader-binary">
		<property desc="" name="fileName" value="KSE.master"></property>
		<property name="skipByteLength" value="10"></property>
		<property name="start-row" value="0"></property>
		<property name="select-rownum" value="3"></property>
		<property name="direction" value="normal"></property>
		<cache>
			<enable>false</enable>
			<expire></expire>
			<max-object-num></max-object-num>
			<event></event>
		</cache>
		<transaction-type></transaction-type>
	</processor-info>

	<input>
		<block></block>
	</input>

	<output>
		<block>
			<field name="data_len" size="4" type="int"></field>
			<field name="TMP" size="2" type="int"></field>
			<field name="jong_code" size="5" type="string"></field>
			<field name="std_code" size="12" type="string"></field>
			<field name="jong_name" size="20" type="string"></field>
			<field name="jong_name_eng" size="20" type="string"></field>
			<field name="junil_close" size="4" type="int"></field>
			<field name="uplimit_price" size="4" type="int"></field>
			<field name="downlimit_price" size="4" type="int"></field>
			<field name="kijunka" size="4" type="int"></field>
			<field name="junil_vol" size="8" type="long"></field>
			<field name="junil_amt" size="8" type="long"></field>
			<field name="akmyunka" size="4" type="int"></field>
			<field name="year_high_date" size="4" type="int"></field>
			<field name="year_high" size="4" type="int"></field>
			<field name="year_low_date" size="4" type="int"></field>
			<field name="year_low" size="4" type="int"></field>
			<field name="list_jusu" size="8" type="long"></field>
			<field name="kwangamli_f" size="1" type="string"></field>
			<field name="trade_stop_f" size="1" type="string"></field>
			<field name="kospi10050_f" size="1" type="string"></field>
			<field name="it_f" size="1" type="string"></field>
			<field name="kospi200_f" size="1" type="string"></field>
			<field name="capital_f" size="1" type="string"></field>
			<field name="up_middle_kospi" size="4" type="int"></field>
			<field name="up_small_kospi" size="4" type="int"></field>
			<field name="manufacture_f" size="2" type="string"></field>
			<field name="venture_f" size="1" type="string"></field>
			<field name="up_group" size="4" type="int"></field>
			<field name="kosdaq50_f" size="1" type="string"></field>
			<field name="kosdaqit50_f" size="1" type="string"></field>
			<field name="up_large" size="4" type="int"></field>
			<field name="up_middle" size="4" type="int"></field>
			<field name="mkt_pr_tot_scale_f" size="1" type="string"></field>
			<field name="stock_type" size="1" type="string"></field>
			<field name="up_code" size="4" type="string"></field>
		</block>
	</output>
	<Signature>
		<SignatureValue>7767b09d42d03ebc6beb47f15932a5d2</SignatureValue>
	</Signature>
</transaction>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/seat/list.xml
<?xml version="1.0" encoding="UTF-8" ?>

<transaction name=""  xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
  <info>
    <name>list</name>
    <description>좌석목록</description>
    <author>김소영</author>
    <version></version>
    <http-access>true</http-access>
  </info>
  
  <processor-info type="dbms" datasource="ksyboard">
    <transaction-type></transaction-type>
    <sql id="listTheaterinfo">
      <query>
        <![CDATA[
          SELECT theater.tno, theater.name, theater.mno, theater.ano, theaterinfo.tino, TO_CHAR(theaterinfo.time, 'HH24:MI'),
                 theaterinfo.seatlimit, movie.name, movie.age, movie.fileurl, movie.price, area.name
          FROM theater INNER JOIN theaterinfo ON theater.tno = theaterinfo.tno AND theaterinfo.tino = :tino
                       INNER JOIN movie ON theater.mno = movie.mno
                       INNER JOIN area ON theater.ano = area.ano
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>theater.tno, theater.name, theater.mno, theater.ano, theaterinfo.tino, theaterinfo.time,
          theaterinfo.seatlimit, movie.name, movie.age, movie.fileurl, movie.price, area.name</getProperty>
      </mapping>
    </sql>
    <sql id="listSeat">
      <query>
        <![CDATA[
          SELECT seatnum FROM seat WHERE tino = :tino
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>seatnum</getProperty>
      </mapping>
    </sql>
  </processor-info>
  
  <input>
    <block name="InBlock_1">
      <field name="tino" type="string" label="상영관정보번호"></field>
    </block>
  </input>
  
  <output>
    <block name="OutBlock_1">
      <field name="theaterinfo.tino" type="string" label="상영정보번호"></field>
      <field name="theaterinfo.time" type="string" label="상영시간"></field>
      <field name="theaterinfo.seatlimit" type="string" label="전체좌석"></field>
      <field name="theater.tno" type="string" label="상영관번호"></field>
      <field name="theater.name" type="string" label="상영관이름"></field>
      <field name="theater.mno" type="string" label="영화번호"></field>
      <field name="theater.ano" type="string" label="지역번호"></field>
      <field name="area.name" type="string" label="지역이름"></field>
      <field name="movie.age" type="string" label="관람가"></field>
      <field name="movie.fileurl" type="string" label="영화이미지"></field>
      <field name="movie.name" type="string" label="영화이름"></field>
      <field name="movie.price" type="string" label="영화가격"></field>
      <field name="seatnum" type="string" label="좌석번호"></field>
    </block>
  </output>  

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/member/insert.xml
<?xml version="1.0" encoding="UTF-8" ?>

<transaction name=""  xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
  <info>
    <name>list</name>
    <description>회원등록</description>
    <author>김소영</author>
    <version></version>
    <http-access>true</http-access>
  </info>

  <processor-info type="dbms" datasource="ksyboard">
    <script language="java" import="">
      if(input.getInt("mno") != 0){
        executeSQL("updateMember", connection, input, output);
        executeSQL("insertProfile", connection, input, output);
      } else {
        executeSQL("insert", connection, input, output);
      }
    </script>
    <transaction-type></transaction-type>
    <sql id="insert">
      <query>
        <![CDATA[
          INSERT INTO member(mno, id) VALUES(member_seq.nextval, '${id}')
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty></getProperty>
      </mapping>
    </sql>
    <sql id="updateMember">
      <query>
        <![CDATA[
          UPDATE member SET password='${password}' WHERE mno = :mno
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty></getProperty>
      </mapping>
    </sql>
    <sql id="insertProfile">
      <query>
        <![CDATA[
          INSERT INTO profile(mno, name, gender, birth) VALUES(:mno, '${name}', '${gender}', '${birth}')
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty></getProperty>
      </mapping>
    </sql>
  </processor-info>
  
  <input>
    <block name="InBlock_1">
      <field name="id" type="string" label="회원아이디"></field>
      <field name="mno" type="int" label="회원번호"></field>
      <field name="password" type="string" label="암호"></field>
      <field name="name" type="string" label="이름"></field>
      <field name="gender" type="string" label="성별"></field>
      <field name="birth" type="string" label="생일"></field>
    </block>
  </input>
  
  <output>
    <block name="OutBlock_1">
    </block>
  </output>  

</transaction>

=== soyoungkim9/cyberProject/coreBoard/webapp/WEB-INF/coreframe/bld/samples/database/readCity.xml
<?xml version="1.0" encoding="euc-kr" ?>

<transaction name="readCity" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<name>도시 정보 보기</name>
		<description></description>
		<author></author>
		<version></version>
		<http-access>false</http-access>
	</info>

	<processor-info type="dbms" datasource="derbyPool">

		<sql id="query1">
			<query><![CDATA[
      SELECT CITY_ID, CITY_NAME, COUNTRY, AIRPORT, LANGUAGE, COUNTRY_ISO_CODE 
      FROM CITIES WHERE city_id=:id      
      ]]></query>
			<mapping>
				<setProperty></setProperty>
				<getProperty>id,name,country,airport,language,countryIsoCode</getProperty>
			</mapping>
		</sql>

	</processor-info>

	<input>
		<block>
			<field name="id" type="int" />
		</block>
	</input>

	<output>
		<block name="city">
			<field name="id" type="int" />
			<field name="name" type="string" />
			<field name="country" type="string" />
			<field name="airport" type="string" />
			<field name="language" type="string" />
			<field name="countryIsoCode" type="string" />
		</block>
	</output>

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/samples/webponent/chart/t2sfpg8chart2.xml
<?xml version="1.0" encoding="EUC-KR"?>
 <!-- protocolName="db1" -->
<transaction name="t2sfpg8chart2" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
<processor-info datasource="" type="dbms">
  <cache>
    <enable>true</enable>
    <expire>600</expire>
    <max-object-num>100</max-object-num>
  </cache>

<script language="java" import="">
<![CDATA[

//executeSQL("query1", connection, input, output);

try {
  executeSQL("drop", connection, input, output);
}catch(Exception e) {}

try {
  executeSQL("create", connection, input, output);
}catch(Exception e) {}


  executeSQL("query2", connection, input, output);

  for(int i=0;i<output.getCount("SECTOR_NM");i++){
	if(output.getText("SECTOR_NM",i).length()<5){
		output.put("SECTOR_NM", output.getText("SECTOR_NM",i).substring(0,output.getText("SECTOR_NM",i).length()),i);
	}
	else{
		output.put("SECTOR_NM", output.getText("SECTOR_NM",i).substring(0,5),i);
	}
  }


try {
  executeSQL("drop", connection, input, output);
}catch(Exception e) {}  


if( output.getCount("SECTOR_NM") == 0) {

  output.put("SECTOR_NM", " ");
  output.put("SEC_STOCK_WG", "0");
  output.put("MKT_RATIO", "0");
  output.put("SECTOR_AM_SUM", "0");
}

]]>
</script>

  <transaction-type></transaction-type>
  
 <sql id="query1">
    <query>
SELECT ISNULL(SUM(SECTOR_AM), 100000000)
FROM MONTHLY_FUND_STK_INDUSTRY a, FUND_MASTER b
WHERE a.FUND_CD=b.FUND_CD
AND a.SECTOR_CD='I.001'
AND a.DT=(SELECT MAX(DT) FROM MONTHLY_FUND_STK_INDUSTRY WHERE DT &lt;=? AND SECTOR_CD='I.001')
AND CLASS_CD= ?
  
at isolation 0
	</query>
    <mapping>
      <setProperty>DT,CLASS_CD</setProperty>
      <getProperty>SUM_KOSPI</getProperty>
    </mapping>
  </sql>  
  
  
  <sql id="query2">
    <query>


INSERT INTO  #jusik1(SECTOR_CD, CLASS_CD, SECTOR_AM_SUM)
SELECT SECTOR_CD, CLASS_CD, AVG(SEC_STOCK_MKT_WG)
FROM MONTHLY_FUND_STK_INDUSTRY a, FUND_MASTER b
WHERE a.FUND_CD = b.FUND_CD
AND a.DT=(SELECT MAX(DT) FROM MONTHLY_FUND_STK_INDUSTRY a, FUND_MASTER b WHERE a.FUND_CD = b.FUND_CD
AND DT &lt;=? AND CLASS_CD = ?)
AND CLASS_CD = ?
AND SECTOR_CD in (
'I.005', 'I.006', 'I.007', 'I.008' , 'I.009' , 'I.010' ,
'I.011', 'I.012', 'I.013', 'I.014' , 'I.015' , 
'I.016', 'I.017', 'I.018', 'I.019' , 'I.020' , 
'I.021', 'I.022', 'I.023', 'I.024' , 'I.025' , 'I.026'
)
GROUP BY SECTOR_CD, CLASS_CD

SET ROWCOUNT 5

SELECT d.IndustNm, a.SEC_STOCK_MKT_WG, CASE WHEN b.MKT_RATIO = NULL THEN 0 ELSE b.MKT_RATIO END, c.SECTOR_AM_SUM
FROM MONTHLY_FUND_STK_INDUSTRY a, MONTHLY_BM_ANL b, #jusik1 c, FAMASTER.dbo.FAA_STK_INDUSTRY_INFO d
WHERE a.DT=(SELECT MAX(DT) FROM MONTHLY_FUND_STK_INDUSTRY WHERE DT &lt;=? AND SECTOR_CD='I.001')  
AND b.DT=(SELECT MAX(DT) FROM MONTHLY_FUND_STK_INDUSTRY WHERE DT &lt;=? AND SECTOR_CD='I.001')  
AND a.FUND_CD=?
--AND a.FUND_CD = c.FUND_CD
AND a.SECTOR_CD=c.SECTOR_CD
AND a.SECTOR_CD in (
'I.005', 'I.006', 'I.007', 'I.008' , 'I.009' , 'I.010' ,
'I.011', 'I.012', 'I.013', 'I.014' , 'I.015' , 
'I.016', 'I.017', 'I.018', 'I.019' , 'I.020' , 
'I.021', 'I.022', 'I.023', 'I.024' , 'I.025' , 'I.026'
)
AND a.SECTOR_CD=b.BM_CD
AND a.SECTOR_CD=d.IndustCd
ORDER BY a.SEC_STOCK_WG DESC

at isolation 0

SET ROWCOUNT 0


	</query>
    <mapping>
      <setProperty>DT,CLASS_CD,CLASS_CD,DT,DT,FUND_CD</setProperty>
      <getProperty>SECTOR_NM, SEC_STOCK_WG, MKT_RATIO, SECTOR_AM_SUM</getProperty>
    </mapping>
  </sql>
  
   <sql id="drop">
    <query>DROP TABLE #jusik1</query>
    <mapping>
      <setProperty></setProperty>
      <getProperty></getProperty>
    </mapping>
  </sql>


   <sql id="create">
    <query>
    create table #jusik1
( 

SECTOR_CD char(7) null, 
CLASS_CD char(13) null, 
SECTOR_AM_SUM numeric(27,20) null
)
    
    </query>
    <mapping>
      <setProperty></setProperty>
      <getProperty></getProperty>
    </mapping>
  </sql>
     
</processor-info>

<input>
  <block name="arg" repeat="1">
    <field name="DT" type="string" default="20050701"></field>
  	<field name="FUND_CD" type="string" default="KR5105354777"></field>
  	<field name="CLASS_CD" type="string" default="1030201111000"></field>
  </block>
</input>

<output>
  <block name="result" repeat="">
	<field label="업종명"	name="SECTOR_NM"		size="66"	type="string" properties="grid-align:M"></field>
    <field label="펀드"		name="SEC_STOCK_WG"		size="70"	type="string" format="#,##0.00" properties="grid-group-name:{$YEAR};grid-group-size:4"></field>
    <field label="시장"		name="MKT_RATIO"		size="70"	type="string" format="#,##0.00"></field>
    <field label="유형"		name="SECTOR_AM_SUM"	size="70"	type="string" format="#,##0.00"></field>
  </block>
  
  
  <block name="temp" repeat="">
    <field label="합계"		name="SUM_KOSPI"	size="50"	type="float" default='1'></field>
	<field label="합계"		name="SUM"			size="50"	type="float" default='0'></field>
  </block>
  
    
</output>

</transaction>

=== soyoungkim9/cyberProject/coreBoard/webapp/WEB-INF/coreframe/bld/samples/database/basic/insert.xml
<?xml version="1.0" encoding="EUC-KR"?>
<!-- protocolName="db1" -->
<transaction name="insert" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<status>confirmation</status>
		<http-access>false</http-access>
		<effective-date></effective-date>
		<description>일반적인 sql insert 예제</description>
		<version>0.1</version>
		<name></name>
	</info>

	<processor-info datasource="derbyPool" type="dbms">
		<cache>
			<enable>false</enable>
			<expire></expire>
			<max-object-num></max-object-num>
			<event></event>
		</cache>
		<transaction-type>rollback</transaction-type>
		<sql id="sel1">
			<query>SELECT max(city_id)+1 FROM  cities</query>
			<mapping>
				<setProperty></setProperty>
				<getProperty>max</getProperty>
			</mapping>
		</sql>
		<sql id="ins1">
			<query>INSERT INTO cities  (city_id,city_name,country,airport,language,country_iso_code ) 
      VALUES (?,?,?,?,?,?)</query>
			<mapping>
				<setProperty>max,city_name,country,airport,language,country_iso_code</setProperty>
				<getProperty></getProperty>
			</mapping>
		</sql>

	</processor-info>
	<input>
		<block name="contries" repeat="1">
			<field default="100" label="ID" name="city_id" type="string"></field>
			<field default="Amsterdam" label="도시명" name="city_name" type="string"></field>
			<field default="Netherlands" label="국가명" name="country" type="string"></field>
			<field default="AMS" label="공항" name="airport" type="string"></field>
			<field default="Dutch" label="language" name="language" type="string"></field>
			<field default="NL" label="ISO CODE" name="country_iso_code"
				type="string"></field>
		</block>
	</input>
	<output>
		<block>
			<field default="100" label="ID" name="max" type="string"></field>
		</block>
	</output>

	<Signature>
		<SignatureValue>96a5f4d0c5d4618e77107cd4af8f0c578</SignatureValue>
	</Signature>
</transaction>
