=== soyoungkim9/cyberProject/ksy-movie/webapp/coreframe/eclipse/bld-5.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- edited by Sungkwon Kim (CyberImagination, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cyber-i.com/xml/bld"
	targetNamespace="http://www.cyber-i.com/xml/bld">
	<xs:element name="version" default="0.1">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="transaction-type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="" />
				<xs:enumeration value="transction" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="transaction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="info" />
				<xs:element ref="processor-info" />
				<xs:element ref="input" />
				<xs:element ref="output" />
				<xs:element ref="test" minOccurs="0" />
				<xs:element ref="Signature" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="test">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="status" default="developing">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="" />
				<xs:enumeration value="developing" />
				<xs:enumeration value="ready-confirm" />
				<xs:enumeration value="confirmation" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query" />
				<xs:element ref="mapping" />
			</xs:sequence>
			<xs:attribute name="max-rows" type="xs:positiveInteger" use="optional" default="100" />
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="setProperty" type="xs:string" />
	<xs:element name="script" default="//insert Java Code">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="language" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="java" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="import" use="optional" default="java.io.*,java.util.*">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="query">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="" />
								<xs:enumeration value="normal" />
								<xs:enumeration value="batch" />
								<xs:enumeration value="storedprocedure" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="property" >
					<xs:complexType>
						<xs:attribute name="name" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="soap.url" />
									<xs:enumeration value="soap.action" />
									<xs:enumeration value="http.encoding" />
									<xs:enumeration value="http.method" />
									<xs:enumeration value="http.url" />
									<xs:enumeration value="mail.smtp_host" />
									<xs:enumeration value="mail.auth.id" />
									<xs:enumeration value="mail.auth.pwd" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="value" use="required" />
						<xs:attribute name="desc" type="xs:string" />
					</xs:complexType>
				</xs:element>
				
				
	<xs:element name="processor-info">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transaction-type" minOccurs="0" />
				
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded">
					
				</xs:element>
				
				<xs:element ref="cache" minOccurs="0" />
				<xs:element ref="script" minOccurs="0" />
				<xs:element ref="sql" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="dbms" />
						<xs:enumeration value="soap" />
						<xs:enumeration value="http" />
						<xs:enumeration value="java" />
						<xs:enumeration value="mail" />
						<xs:enumeration value="file-reader" />
						<xs:enumeration value="file-writer" />
						<xs:enumeration value="file-reader-binary" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="datasource">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="block" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="setProperty" />
				<xs:element ref="getProperty" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="block" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="xml-document" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="info">
		<xs:complexType>
			<xs:all>
				<xs:element ref="name" minOccurs="0" maxOccurs="1" />
				<xs:element ref="description" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="version" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="author" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="http-access" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="status" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="effective-date" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="http-access" type="xs:boolean" default="false" />
	<xs:element name="getProperty">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:attribute name="value">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="string" />
						<xs:enumeration value="int" />
						<xs:enumeration value="double" />
						<xs:enumeration value="float" />
						<xs:enumeration value="clob" />
						<xs:enumeration value="datetime" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="properties">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xpath">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="default">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="format">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="decimal">
				<xs:simpleType>
					<xs:restriction base="xs:int" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="size" type="xs:positiveInteger" />
			<xs:attribute name="label" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	
	
  <xs:element name="enable" type="xs:string" default="false" />
  <xs:element name="expire" type="xs:positiveInteger" default="60"/>
	<xs:element name="effective-date" type="xs:string" />
	<xs:element name="group" type="xs:string" />
  <xs:element name="max-object-num" type="xs:positiveInteger" default="100"/>
  <xs:element name="event">
    <xs:complexType />
  </xs:element>
  
  
  
	<xs:element name="description" type="xs:string" default="write BLD Description" />
  
  <xs:element name="test-input">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
  
	<xs:element name="case">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="test-input"/>
        
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="cache">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enable"/>
				<xs:element ref="expire" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="max-object-num" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="group" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="event"  minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="block">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="repeat" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xpath" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="ref" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="class" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="xml-document">
		<xs:complexType />
	</xs:element>
	<xs:element name="SignatureValue">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="Signature">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SignatureValue" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/samples/database/clob/insertXTM.xml
<?xml version="1.0" encoding="EUC-KR"?>
<!-- protocolName="db1" -->
<transaction name="insertXTM" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<processor-info datasource="taxonomyPool" type="dbms">

		<script language="java"
			import="coreframe.log.*,coreframe.util.*,java.io.*,java.sql.*,oracle.sql.CLOB">
			<![CDATA[  

		  // 기본 데이터 입력  실행
		  executeSQL("query1", connection, input, output);
		  executeSQL("query2", connection, input, output);
		  executeSQL("query3", connection, input, output);
		
		  try {
		
		
		    Statement tmp=connection.createStatement();
		    Connection oracleConnection = tmp.getConnection();
		    oracle.sql.CLOB clob = CLOB.createTemporary( oracleConnection, true, CLOB.DURATION_SESSION );
		    //tmp.close();
		    
		    String ctnt = input.getText("FL_BD");
		    
		
		    //encoding 변경 필요시
		    //xmlText = new String(xmlText.getBytes("euc-kr"), "ISO8859_1");
		    clob.putString(1,ctnt);
		
		    String UPDATE_STATEMENT_TEXT = "UPDATE TBL_XTM_002 SET FL_BD=XMLTYPE(?) WHERE TXN_FL_SEQ_NO=?";
		    CallableStatement updateStatement = connection.prepareCall( UPDATE_STATEMENT_TEXT );
		    
		    updateStatement.setClob(1, clob );
		    updateStatement.setString(2, output.getText("FILE_SEQ") );
		    updateStatement.execute();
		    //clob.trim(0);
		    //clob.freeTemporary();
		    
		    updateStatement.close();
		
		  } 
		  catch(Exception ee) 
		  {
		    //ee.printStackTrace();
		    Logger.err.println("insertXTM_002.xml error",ee);
		    throw ee;
		  }      

  ]]>
		</script>
		<transaction-type>rollback</transaction-type>


		<sql id="query1">
			<query>
				SELECT DECODE(MAX(TXN_FL_SEQ_NO), '', 0,
				MAX(TXN_FL_SEQ_NO))+1 FROM TBL_XTM_002
			</query>
			<mapping>
				<setProperty></setProperty>
				<getProperty>FILE_SEQ</getProperty>
			</mapping>
		</sql>
		<sql id="query2">
			<query>
				SELECT CD_ID FROM TBL_XCC_001 WHERE CD_ENG_NM = ?
			</query>
			<mapping>
				<setProperty>TXN_FL_TP</setProperty>
				<getProperty>TXN_FL_CD</getProperty>
			</mapping>
		</sql>
		<sql id="query3">
			<query>
				INSERT INTO TBL_XTM_002 (TXN_FL_SEQ_NO, TXN_SEQ_NO,
				TXN_FL_TP, FL_NM) VALUES (?, ?, ?, ?)
			</query>
			<mapping>
				<setProperty>
					FILE_SEQ, TXN_SEQ_NO, TXN_FL_CD, FL_NM
				</setProperty>
				<getProperty></getProperty>
			</mapping>
		</sql>
	</processor-info>

	<input>
		<block name="arg" repeat="1">
			<field name="TXN_SEQ_NO" type="int"></field>
			<field name="TXN_FL_TP" type="string"></field>
			<field name="FL_NM" type="string"></field>
			<field name="FL_BD" type="string"></field>
		</block>
	</input>

	<output>
		<block name="result" repeat="">
			<field name="FILE_SEQ" type="int"></field>
			<field name="TXN_FL_CD" type="string"></field>
		</block>
	</output>

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/system/msg/insertLog.xml
<?xml version="1.0" encoding="UTF-8"?>

<transaction name="insertLog" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<name>insertLog</name>
		<http-access>false</http-access>
		<effective-date></effective-date>
		<description>insert coreFRAME performance log</description>
		<version>0.1</version>
	</info>

	<processor-info type="dbms" datasource="cf-system">
		<transaction-type></transaction-type>

		<sql id="ins1">
			<query>INSERT INTO APP.CF_SERVERMSG
				(SERVERID, TSDATE,
				TSTIME,TYPE, TITLE,MSG,TS)
				VALUES
				(:SERVERID, :TSDATE, :TSTIME, 
				:TYPE, :TITLE, :MSG, :TS )
			</query>
			<mapping>
				<setProperty></setProperty>
				<getProperty></getProperty>
			</mapping>
		</sql>
	</processor-info>


	<input>
		<block name="performance" repeat="1">
			<field name="SERVERID" type="string" />
			<field name="TSDATE" type="string" />
			<field name="TSTIME" type="string" />
			<field name="TYPE" type="string" />
			<field name="TITLE" type="string" />
			<field name="MSG" type="string" />
			<field name="TS" type="datetime" />
		</block>
	</input>

	<output>
		<block>

		</block>
	</output>

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/samples/database/clob/insert.xml
<?xml version='1.0' encoding='euc-kr'?>

<!-- protocolName='db1' -->
<transaction name='insert' xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">



	<processor-info type='dbms' datasource=''>
		<transaction-type>rollback</transaction-type>

		<sql id='1'>
			<query>SELECT NVL(MAX(no),0)+1 FROM xbrl_instance</query>
			<mapping>
				<setProperty></setProperty>
				<getProperty>no</getProperty><!-- seq -->
			</mapping>
		</sql>

		<sql id='run1'>
			<query type="storedprocedure">

DECLARE
  poXML CLOB;
  

BEGIN
  poXML := '$xbrl';
  
  INSERT INTO xbrl_instance (no,code,version,company,xbrl,  create_date,create_time)
	        VALUES ($seq,?,?,?,XMLTYPE(poXML),to_char(sysdate,'YYMMDD'),to_char(sysdate,'HHMISS'));
END;

	        
	        </query>
			<mapping>
				<setProperty>code,version,company</setProperty>
				<getProperty></getProperty>
			</mapping>
		</sql>


	</processor-info>


	<input>
		<block>

			<field name="code" type="string" />
			<field name="version" type="string" />
			<field name="company" type="string" />
			<field name="xbrl" type="string" />
			<field name="style_xbrl" type="string" />
		</block>
	</input>

	<output>
		<block>
			<field name="seq" type="string" />
		</block>
	</output>

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/src/main/webapp/WEB-INF/coreframe/bld/movie/list.xml
<?xml version="1.0" encoding="UTF-8" ?>

<transaction name=""  xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
  <info>
    <name>list</name>
    <description>영화목록 리스트</description>
    <author>김소영</author>
    <version></version>
    <http-access>true</http-access>
  </info>
  
  <processor-info type="dbms" datasource="ksyboard">
    <script language="java" import="">
      String type1 = input.getText("tab1");
      if(type1.equals("tab1_expected")) {
        executeSQL("listExpected", connection, input, output);
      } else if (input.get("mno") != "" &amp;&amp; input.get("i") != "") {
        executeSQL("listSelectGrade", connection, input, output);
      } else if (input.get("mno") != "" &amp;&amp; input.get("j") != "") {
        executeSQL("listSelectReserve", connection, input, output);
        executeSQL("listSeatTotal", connection, input, output);
      } else if(type1.equals("tab1_current_grade")) {
        executeSQL("listGrade", connection, input, output);
      } else {
        executeSQL("listCurrent", connection, input, output);
        executeSQL("listSeatTotal", connection, input, output);
      }
    </script>
    <transaction-type></transaction-type>
    <sql id="listCurrent">
      <query>
        <![CDATA[
          SELECT movie.mno, name, sdt, age, genre, fileurl, COUNT(*) AS mCnt
          FROM movie LEFT OUTER JOIN seat
          ON movie.mno = seat.mno
          WHERE sdt < (SELECT SYSDATE FROM DUAL)
          GROUP BY movie.mno, name, sdt, age, genre, fileurl
          ORDER BY mCnt DESC
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>mno, name, sdt, age, genre, fileurl, mCnt</getProperty>
      </mapping>
    </sql>
    <sql id="listExpected">
      <query>
        <![CDATA[
          SELECT mno, name, sdt, age, genre, fileurl FROM movie
          WHERE sdt > (SELECT SYSDATE FROM DUAL)
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>mno, name, sdt, age, genre, fileurl</getProperty>
      </mapping>
    </sql>
    <sql id="listSeatTotal">
      <query>
        <![CDATA[
          SELECT COUNT(*) AS stotal FROM seat
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>stotal</getProperty>
      </mapping>
    </sql>
    <sql id="listSelectGrade">
      <query>
        <![CDATA[
          SELECT SUM(GRADE) AS gsum, COUNT(mno) AS gcnt, mno FROM comments WHERE mno = :mno GROUP BY mno
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>gsum, gcnt, mno</getProperty>
      </mapping>
    </sql>
    <sql id="listGrade">
      <query>
        <![CDATA[
          SELECT m.mno, name, sdt, age, genre, fileurl, ROUND(NVL(SUM(NULLIF(c.grade, 0))/COUNT(c.mno), 0), 1) AS result, SUM(NVL(c.grade,0)) AS gsum, COUNT(c.mno) AS gcnt
          FROM movie m FULL OUTER JOIN comments c
          ON m.mno = c.mno
          WHERE sdt < (SELECT SYSDATE FROM DUAL)
          GROUP BY m.mno, name, sdt, age, genre, fileurl
          ORDER BY result DESC
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>mno, name, sdt, age, genre, fileurl, result, gsum, gcnt</getProperty>
      </mapping>
    </sql>
    <sql id="listSelectReserve">
      <query>
        <![CDATA[
          SELECT mno, COUNT(*) AS mCnt FROM seat WHERE mno = :mno GROUP BY mno
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>mno, mCnt</getProperty>
      </mapping>
    </sql>
  </processor-info>
  
  <input>
    <block name="InBlock_1">
      <field name="mno" type="string" label="영화번호"></field>
    </block>
  </input>
  
  <output>
    <block name="OutBlock_1">
      <field name="mno" type="string" label="영화번호"></field>
      <field name="name" type="string" label="영화이름"></field>
      <field name="age" type="string" label="관람나이"></field>
      <field name="sdt" type="string" label="개봉일"></field>
      <field name="genre" type="string" label="장르번호"></field>
      <field name="fileurl" type="string" label="영화이미지"></field>
      <field name="mCnt" type="int" label="예매수"></field>
      <field name="stotal" type="int" label="좌석예매전체"></field>
      <field name="gsum" type="int" label="평점합계"></field>
      <field name="gcnt" type="int" label="평점개수"></field>
      <field name="result" type="double" label="평점평균"></field>
    </block>
  </output>  

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/src/main/webapp/WEB-INF/coreframe/bld/system/msg/listLog.xml
<?xml version="1.0" encoding="UTF-8"?>

<transaction name="listLog" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<name>listLog</name>
		<http-access>false</http-access>
		<effective-date></effective-date>
		<description>insert coreFRAME performance log</description>
		<version>0.1</version>
	</info>

	<processor-info type="dbms" datasource="cf-system">
		<transaction-type></transaction-type>

		<sql id="ins1" max-rows="10">
			<query>SELECT 
                 SERVERID, TSDATE, TSTIME,TYPE, TITLE,MSG,TS
				FROM APP.CF_SERVERMSG 
				WHERE TYPE= :TYPE
				ORDER BY TSDATE DESC, TSTIME DESC
				</query>
			<mapping>
				<setProperty></setProperty>
				<getProperty>SERVERID, TSDATE, TSTIME,TYPE, TITLE,MSG,TS
				</getProperty>
			</mapping>
		</sql>
	</processor-info>


	<input>
		<block>
             <field name="TYPE" type="string" default="E" />
		</block>
	</input>

	<output>
		<block name="performance" repeat="1">
			<field name="SERVERID" type="string" />
			<field name="TSDATE" type="string" />
			<field name="TSTIME" type="string" format="HHmmss->HH:mm:ss"/>
			
			<field name="TYPE" type="string" />
			<field name="TITLE" type="string" />
			<field name="MSG" type="string" />
			<field name="TS" type="string" />
			
		</block>
	</output>

</transaction>

=== soyoungkim9/cyberProject/coreBoard/webapp/WEB-INF/coreframe/bld/samples/misc/useModel.xml
<?xml version="1.0" encoding="EUC-KR"?>
<transaction name="useModel" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<status>confirmation</status>
		<http-access>false</http-access>
		<effective-date></effective-date>
		<description>모델정보를 재활용한다.</description>
		<version>0.1</version>
		<name>모델정보 import</name>
	</info>

	<processor-info datasource="derbyPool" type="dbms">
		<cache>
			<enable>false</enable>
			<expire></expire>
			<max-object-num></max-object-num>
			<event></event>
		</cache>
		<transaction-type></transaction-type>
		<sql id="sel1">
			<query>SELECT city_id,city_name,country,airport,language,country_iso_code 
FROM CITIES WHERE city_name like '${city_name}%'</query>
			<mapping>
				<setProperty></setProperty>
				<getProperty>city_id,city_name,country,airport,language,country_iso_code</getProperty>
			</mapping>
		</sql>

	</processor-info>

	<input>
		<block>
			<field default="S" name="city_name" type="string"></field>
		</block>
	</input>

	<!-- <output>
		<block id="samples/misc/basicModel.city" name="arg"repeat="1">
			
		</block>
	</output> -->
	<output>
		<block>
			<field label="ID" name="city_id" type="string"></field>
			<field label="도시명" name="city_name" type="string"></field>
			<field label="국가명" name="country" type="string"></field>
			<field label="공항" name="airport" type="string"></field>
			<field label="language" name="language" type="string"></field>
			<field label="ISO CODE" name="country_iso_code" type="string"></field>
		</block>
	</output>

	<Signature>
		<SignatureValue>817ef644279a508d709351a9ea109bfb0</SignatureValue>
	</Signature>
</transaction>

=== soyoungkim9/cyberProject/coreBoard/webapp/WEB-INF/coreframe/bld/samples/http/cosComStock.xml
<?xml version="1.0" encoding="EUC-KR"?>
<transaction name="cosComStock" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<info>
		<effective-date></effective-date>
		<description>cosCom 으로 부터 증권 주가 정보를 가져온다.</description>
		<version>0.1</version>
		<name>cosCom 주가정보</name>
		<status>confirmation</status>
		<http-access>false</http-access>
	</info>
	<processor-info type="http">
		<property desc="http 통신 method" name="http.method" value="GET"></property>
		<property desc="http encoding" name="http.encoding" value="EUC-KR"></property>
		<property desc="http url" name="http.url"
			value="http://stock.koscom.co.kr/jisu/jisu.xml"></property>


	</processor-info>
	<input>
	</input>
	<output>
		<block id="user" name="result" repeat="" xpath="/market/data">
			<field name="title" type="string" xpath="title"></field>
			<field name="jangdate" type="string" xpath="jangdate"></field>
			<field name="jangtime" type="string" xpath="jangtime"></field>
			<field name="jisu" type="string" xpath="jisu"></field>
			<field name="buho" type="string" xpath="buho"></field>
			<field name="daebi" type="string" xpath="daebi"></field>
			<field name="vol" type="string" xpath="vol"></field>
			<field name="amt" type="string" xpath="amt"></field>
		</block>
	</output>
	<Signature>
		<SignatureValue>1d78436d9bb51b113b289e57ba04ae9b4</SignatureValue>
	</Signature>
</transaction>
