=== soyoungkim9/cyberProject/ksy-movie/webapp/coreframe/eclipse/bld-5.0.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- edited by Sungkwon Kim (CyberImagination, Inc.) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.cyber-i.com/xml/bld"
	targetNamespace="http://www.cyber-i.com/xml/bld">
	<xs:element name="version" default="0.1">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="transaction-type">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="" />
				<xs:enumeration value="transction" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="transaction">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="info" />
				<xs:element ref="processor-info" />
				<xs:element ref="input" />
				<xs:element ref="output" />
				<xs:element ref="test" minOccurs="0" />
				<xs:element ref="Signature" minOccurs="0" />
			</xs:sequence>
			<xs:attribute name="name" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="test">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="case" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="status" default="developing">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="" />
				<xs:enumeration value="developing" />
				<xs:enumeration value="ready-confirm" />
				<xs:enumeration value="confirmation" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="sql">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="query" />
				<xs:element ref="mapping" />
			</xs:sequence>
			<xs:attribute name="max-rows" type="xs:positiveInteger" use="optional" default="100" />
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="setProperty" type="xs:string" />
	<xs:element name="script" default="//insert Java Code">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="language" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="java" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="import" use="optional" default="java.io.*,java.util.*">
						<xs:simpleType>
							<xs:restriction base="xs:string" />
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="query">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="type" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="" />
								<xs:enumeration value="normal" />
								<xs:enumeration value="batch" />
								<xs:enumeration value="storedprocedure" />
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="property" >
					<xs:complexType>
						<xs:attribute name="name" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="soap.url" />
									<xs:enumeration value="soap.action" />
									<xs:enumeration value="http.encoding" />
									<xs:enumeration value="http.method" />
									<xs:enumeration value="http.url" />
									<xs:enumeration value="mail.smtp_host" />
									<xs:enumeration value="mail.auth.id" />
									<xs:enumeration value="mail.auth.pwd" />
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="value" use="required" />
						<xs:attribute name="desc" type="xs:string" />
					</xs:complexType>
				</xs:element>
				
				
	<xs:element name="processor-info">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="transaction-type" minOccurs="0" />
				
				<xs:element ref="property" minOccurs="0" maxOccurs="unbounded">
					
				</xs:element>
				
				<xs:element ref="cache" minOccurs="0" />
				<xs:element ref="script" minOccurs="0" />
				<xs:element ref="sql" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="dbms" />
						<xs:enumeration value="soap" />
						<xs:enumeration value="http" />
						<xs:enumeration value="java" />
						<xs:enumeration value="mail" />
						<xs:enumeration value="file-reader" />
						<xs:enumeration value="file-writer" />
						<xs:enumeration value="file-reader-binary" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="datasource">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="output">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="block" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="name">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="mapping">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="setProperty" />
				<xs:element ref="getProperty" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="input">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="block" minOccurs="0" maxOccurs="unbounded" />
				<xs:element ref="xml-document" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="info">
		<xs:complexType>
			<xs:all>
				<xs:element ref="name" minOccurs="0" maxOccurs="1" />
				<xs:element ref="description" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="version" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="author" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="http-access" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="status" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="effective-date" minOccurs="0" maxOccurs="1"/>
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:element name="http-access" type="xs:boolean" default="false" />
	<xs:element name="getProperty">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="field">
		<xs:complexType>
			<xs:attribute name="value">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="string" />
						<xs:enumeration value="int" />
						<xs:enumeration value="double" />
						<xs:enumeration value="float" />
						<xs:enumeration value="clob" />
						<xs:enumeration value="datetime" />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="properties">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xpath">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="default">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="format">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="decimal">
				<xs:simpleType>
					<xs:restriction base="xs:int" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="size" type="xs:positiveInteger" />
			<xs:attribute name="label" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
	
	
  <xs:element name="enable" type="xs:string" default="false" />
  <xs:element name="expire" type="xs:positiveInteger" default="60"/>
	<xs:element name="effective-date" type="xs:string" />
	<xs:element name="group" type="xs:string" />
  <xs:element name="max-object-num" type="xs:positiveInteger" default="100"/>
  <xs:element name="event">
    <xs:complexType />
  </xs:element>
  
  
  
	<xs:element name="description" type="xs:string" default="write BLD Description" />
  
  <xs:element name="test-input">
          <xs:complexType>
            <xs:sequence>
              <xs:element ref="field" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
  
	<xs:element name="case">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="test-input"/>
        
			</xs:sequence>
			<xs:attribute name="name" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="cache">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="enable"/>
				<xs:element ref="expire" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="max-object-num" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="group" minOccurs="0" maxOccurs="1"/>
				<xs:element ref="event"  minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="block">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="field" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="name" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="repeat" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="xpath" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			
			<xs:attribute name="ref" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string" />
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="class" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="author">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="xml-document">
		<xs:complexType />
	</xs:element>
	<xs:element name="SignatureValue">
		<xs:simpleType>
			<xs:restriction base="xs:string" />
		</xs:simpleType>
	</xs:element>
	<xs:element name="Signature">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="SignatureValue" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== soyoungkim9/cyberProject/ksy-movie/src/main/webapp/WEB-INF/coreframe/bld/ticket/list.xml
<?xml version="1.0" encoding="UTF-8" ?>

<transaction name=""  xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
  <info>
    <name>list</name>
    <description>좌석목록</description>
    <author>김소영</author>
    <version></version>
    <http-access>true</http-access>
  </info>
  
  <processor-info type="dbms" datasource="ksyboard">
    <script language="java" import="">
      if(input.getText("id") != "" 	&amp;&amp; input.get("tino") == "") {
        executeSQL("listRandomkey", connection, input, output);
      }
      if(input.getText("tino") != "") {
        executeSQL("listTheaterinfo", connection, input, output);
      }
      if(input.getText("randomkey") != "") {
      executeSQL("listPayment", connection, input, output);
      }
    </script>
    <transaction-type></transaction-type>
    <sql id="listTheaterinfo">
      <query>
        <![CDATA[
          SELECT theater.tno, theater.name, theater.mno, theater.ano, theaterinfo.tino, TO_CHAR(theaterinfo.time, 'HH24:MI'),
                 theaterinfo.seatlimit, movie.name, movie.age, movie.fileurl, movie.price, area.name
          FROM theater INNER JOIN theaterinfo ON theater.tno = theaterinfo.tno AND theaterinfo.tino = :tino
                       INNER JOIN movie ON theater.mno = movie.mno
                       INNER JOIN area ON theater.ano = area.ano
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>theater.tno, theater.name, theater.mno, theater.ano, theaterinfo.tino, theaterinfo.time,
          theaterinfo.seatlimit, movie.name, movie.age, movie.fileurl, movie.price, area.name</getProperty>
      </mapping>
    </sql>
    <sql id="listRandomkey">
      <query>
        <![CDATA[
          SELECT distinct seat.randomkey, id, tino, cdate FROM seat
          INNER JOIN payment ON seat.randomkey = payment.randomkey
          WHERE id LIKE '${id}'
          ORDER BY cdate DESC
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>seat.randomkey, id, tino, cdate</getProperty>
      </mapping>
    </sql>
    <sql id="listPayment">
      <query>
        <![CDATA[
          SELECT count(randomkey) as ticketcount, randomkey, adult, senior, disabled, teenager, charge, cdate
          FROM payment WHERE RANDOMKEY LIKE '${randomkey}'
          GROUP BY randomkey, adult, senior, disabled, teenager, charge, cdate
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>ticketcount, randomkey, adult, senior, disabled, teenager, charge, cdate</getProperty>
      </mapping>
    </sql>
  </processor-info>
  
  <input>
    <block name="InBlock_1">
      <field name="tino" type="string" label="상영관정보번호"></field>
      <field name="id" type="string" label="회원아이디"></field>
      <field name="randomkey" type="string" label="랜덤키"></field>
    </block>
  </input>
  
  <output>
    <block name="OutBlock_1">
      <field name="theaterinfo.tino" type="string" label="상영정보번호"></field>
      <field name="theaterinfo.time" type="string" label="상영시간"></field>
      <field name="theaterinfo.seatlimit" type="string" label="전체좌석"></field>
      <field name="theater.tno" type="string" label="상영관번호"></field>
      <field name="theater.name" type="string" label="상영관이름"></field>
      <field name="theater.mno" type="string" label="영화번호"></field>
      <field name="theater.ano" type="string" label="지역번호"></field>
      <field name="area.name" type="string" label="지역이름"></field>
      <field name="movie.age" type="string" label="관람가"></field>
      <field name="movie.fileurl" type="string" label="영화이미지"></field>
      <field name="movie.name" type="string" label="영화이름"></field>
      <field name="movie.price" type="string" label="영화가격"></field>
      <field name="randomkey" type="string" label="랜덤키"></field>
      <field name="seat.randomkey" type="string" label="랜덤키"></field>
      <field name="adult" type="string" label="성인"></field>
      <field name="senior" type="string" label="노인"></field>
      <field name="disabled" type="string" label="장애인"></field>
      <field name="teenager" type="string" label="청소년"></field>
      <field name="charge" type="string" label="결제금액"></field>
      <field name="ticketcount" type="string" label="티켓수"></field>
      <field name="id" type="string" label="티켓수"></field>
      <field name="tino" type="string" label="상영관정보번호"></field>
      <field name="cdate" type="string" label="예매일"></field>
    </block>
  </output>  

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/src/main/webapp/WEB-INF/coreframe/bld/samples/stockchart/outputList.xml
<?xml version="1.0" encoding="EUC-KR"?>

<transaction name="outputList" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<processor-info datasource="wpfChart" type="dbms">
		<script language="java"><![CDATA[
					
			if("2".equals(input.getText("dateGubun"))) {	//ÁÖºÀ
				executeSQL("weekData", connection, input, output);
			} else if("3".equals(input.getText("dateGubun"))) {	//¿ùºÀ
				executeSQL("monthData", connection, input, output);
			} else {	//ÀÏºÀ	
				if(!"undefined".equals(input.getText("stDate")) && !"".equals(input.getText("stDate"))) {
					executeSQL("dayDataAfter", connection, input, output);
				} else {
					executeSQL("dayData", connection, input, output);	
				}						
			}
			
		]]></script>
		<transaction-type></transaction-type>

		<sql id="dayData">
			<query><![CDATA[
				SELECT TRD_DD, CLSPRC, OPNPRC, HGPRC, LWPRC, TRDVOL, FORN_ORD_LMT_QTY 
				FROM(
				    SELECT ROW_NUMBER() OVER(ORDER BY TRD_DD DESC) num, 
				        TRD_DD, CLSPRC, OPNPRC, HGPRC, LWPRC, TRDVOL, FORN_ORD_LMT_QTY 
				    FROM CHART_TEST_DATA
				    WHERE CODE = ?
				    )
				WHERE num <= 500 
				ORDER BY TRD_DD
				
			]]></query>
			<mapping>
				<setProperty>code</setProperty>
				<getProperty>axis, close, open, high, low, trdvol, forn_ord_lmt_qty</getProperty>
			</mapping>
		</sql>

		<sql id="dayDataAfter">
			<query><![CDATA[
				SELECT TRD_DD, CLSPRC, OPNPRC, HGPRC, LWPRC, TRDVOL, FORN_ORD_LMT_QTY 
				FROM(
				    SELECT ROW_NUMBER() OVER(ORDER BY TRD_DD DESC) num, 
				        TRD_DD, CLSPRC, OPNPRC, HGPRC, LWPRC, TRDVOL, FORN_ORD_LMT_QTY 
				    FROM CHART_TEST_DATA
				    WHERE CODE = ?
				    AND TRD_DD <= ?
				    )
				WHERE num <= 100 
				ORDER BY TRD_DD
				
			]]></query>
			<mapping>
				<setProperty>code, stDate</setProperty>
				<getProperty>axis, close, open, high, low, trdvol, forn_ord_lmt_qty</getProperty>
			</mapping>
		</sql>

		<sql id="weekData">
			<query>
				
				SELECT a.TRD_DD, b.CLSPRC, a.OPNPRC, c.HGPRC, c.LWPRC, c.TRDVOL, a.FORN_ORD_LMT_QTY    FROM
				           
				    (SELECT TRD_DD, OPNPRC, FORN_ORD_LMT_QTY, DENSE_RANK() OVER(ORDER BY TRUNC(TO_DATE(TRD_DD,'yyyymmdd'),'d')) as WEEK 
				    FROM CHART_TEST_DATA 
				        WHERE CODE = ?
				        AND TRD_DD IN (             
				                SELECT MIN(s.TRD_DD) TRD_DD FROM                
				                    (SELECT TRD_DD,
				                        DENSE_RANK() OVER(ORDER BY TRUNC(TO_DATE(TRD_DD,'yyyymmdd'),'d')) as WEEK                         
				                        FROM CHART_TEST_DATA
				                        WHERE CODE = ?                                                                                        
				                    ) s
				                    GROUP BY s.WEEK
				                    )) a,
				         
				    (SELECT TRD_DD, CLSPRC, DENSE_RANK() OVER(ORDER BY TRUNC(TO_DATE(TRD_DD,'yyyymmdd'),'d')) as WEEK 
				    FROM CHART_TEST_DATA 
				        WHERE CODE = ?
				        AND TRD_DD IN (             
				                SELECT MAX(s.TRD_DD) TRD_DD FROM                
				                    (SELECT TRD_DD,
				                        DENSE_RANK() OVER(ORDER BY TRUNC(TO_DATE(TRD_DD,'yyyymmdd'),'d')) as WEEK                         
				                        FROM CHART_TEST_DATA
				                        WHERE CODE = ?                                                                                         
				                    ) s
				                    GROUP BY s.WEEK
				                    )) b,                    
				                    
				    (SELECT MAX(s.HGPRC) HGPRC, MIN(s.LWPRC) LWPRC, SUM(s.TRDVOL) TRDVOL, s.WEEK  FROM                
				                    (SELECT TRD_DD, HGPRC, LWPRC,TRDVOL,
				                        DENSE_RANK() OVER(ORDER BY TRUNC(TO_DATE(TRD_DD,'yyyymmdd'),'d')) as WEEK                         
				                        FROM CHART_TEST_DATA
				                        WHERE CODE = ?                                                                                         
				                    ) s
				                    GROUP BY s.WEEK ) c  
				                     
				     WHERE a.WEEK = b.WEEK
				     AND a.WEEK = c.WEEK
				     ORDER BY a.TRD_DD                              
			</query>
			<mapping>
				<setProperty>code,code,code,code,code</setProperty>
				<getProperty>axis, close, open, high, low, trdvol, forn_ord_lmt_qty</getProperty>
			</mapping>
		</sql>

		<sql id="monthData">
			<query>
				              
				SELECT a.TRD_DD, b.CLSPRC, a.OPNPRC, c.HGPRC, c.LWPRC, c.TRDVOL, a.FORN_ORD_LMT_QTY    
					FROM                 				                
				                 
				    (SELECT TRD_DD, OPNPRC, FORN_ORD_LMT_QTY, SUBSTR(TRD_DD,1,6) YM FROM CHART_TEST_DATA 
				        WHERE CODE = ? 
				        AND TRD_DD IN (                
				                SELECT MIN(TRD_DD) TRD_DD FROM CHART_TEST_DATA GROUP BY SUBSTR(TRD_DD,1,6) 
				                )) a,
				                
				    (SELECT CLSPRC, SUBSTR(TRD_DD,1,6) YM FROM CHART_TEST_DATA 
				        WHERE CODE = ? 
				        AND TRD_DD IN (                
				                SELECT MAX(TRD_DD) TRD_DD FROM CHART_TEST_DATA GROUP BY SUBSTR(TRD_DD,1,6) 
				                )) b,
				                             
				    (SELECT MAX(HGPRC) HGPRC, MIN(LWPRC) LWPRC, SUM(TRDVOL) TRDVOL, SUBSTR(TRD_DD,1,6) YM 
				    	FROM CHART_TEST_DATA 
				    	WHERE CODE = ? 
				    	GROUP BY SUBSTR(TRD_DD,1,6)) c
					WHERE a.YM = b.YM
					AND a.YM = c.YM
					ORDER BY a.TRD_DD 	 
			</query>
			<mapping>
				<setProperty>code,code,code</setProperty>
				<getProperty>axis, close, open, high, low, trdvol, forn_ord_lmt_qty</getProperty>
			</mapping>
		</sql>
	</processor-info>

	<input>
		<block name="arg">
			<field name="code" type="string"></field>
			<field name="stDate" type="string"></field>
			<field name="dateGubun" type="string"></field>
		</block>
	</input>

	<output>
		<block name="result">
			<field name="axis" type="string"></field>
			<field name="close" type="string"></field>
			<field name="open" type="string"></field>
			<field name="high" type="string"></field>
			<field name="low" type="string"></field>
			<field name="trdvol" type="string"></field>
			<field name="forn_ord_lmt_qty" type="string"></field>
		</block>
	</output>

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/src/main/webapp/WEB-INF/coreframe/bld/samples/database/batch/basic.xml
<?xml version="1.0" encoding="EUC-KR"?>

<transaction name="basic" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
	<!-- 1) type 을 batch 로 정의 2) DataSet input 값에 여러개의 값이 미리 들어가 있어야 함. -->
	<processor-info datasource="" type="dbms">
		<transaction-type></transaction-type>
		<sql id="query1">

			<query type="batch">
				DELETE FROM dbo.CLASS_BM WHERE CLASS_CD =? AND SEQ=?

				INSERT INTO dbo.CLASS_BM (CLASS_CD,SEQ,BM_NM,WG) VALUES
				(?,?,?,?)
			</query>
			<mapping>
				<setProperty>
					CLASS_CD,SEQ,CLASS_CD,SEQ,BM_NM,WG
				</setProperty>
				<getProperty></getProperty>
			</mapping>
		</sql>
	</processor-info>

	<input>
		<block name="arg" repeat="1">
			<field label="유형코드" name="CLASS_CD" type="string"></field>
			<field label="순번    " name="SEQ" type="string"></field>
			<field label="시장BM명" name="BM_NM" type="string"></field>
			<field label="합성비율" name="WG" type="float" />

		</block>
	</input>

	<output>
		<block name="result" repeat=""></block>
	</output>

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/webapp/WEB-INF/coreframe/bld/comments/list.xml
<?xml version="1.0" encoding="UTF-8" ?>

<transaction name=""  xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">
  <info>
    <name>list</name>
    <description>댓글관련 리스트</description>
    <author>김소영</author>
    <version></version>
    <http-access>true</http-access>
  </info>
  
  <processor-info type="dbms" datasource="ksyboard">
    <script language="java" import="">
        if(input.get("id") != "" &amp;&amp; input.get("mno") != "") {
          executeSQL("listCharge", connection, input, output);
          executeSQL("listId", connection, input, output);
          executeSQL("listReviewRight", connection, input, output);
        } else if(input.get("startRow") != ""){
          executeSQL("listComments", connection, input, output);
          executeSQL("listCount", connection, input, output);
        }
    </script>
    <transaction-type></transaction-type>
    <sql id="listCharge">
      <query>
        <![CDATA[
          SELECT id, mno FROM seat WHERE id LIKE '${id}' AND mno LIKE :mno
        ]]>
      </query>
      <mapping>
        <setProperty></setProperty>
        <getProperty>id, mno</getProperty>
      </mapping>
    </sql>
    <sql id="listComments">
      <query>
          <![CDATA[
             SELECT rnum, cmo, mno, id, grade, content, TO_CHAR(rdate, 'yyyy.mm.dd')
             FROM (SELECT row_number() OVER(ORDER BY cmo DESC)AS rnum, comments.* FROM comments WHERE mno = :mno) comments
             WHERE rnum > :startRow  AND rnum <= :startRow + :size
           ]]>
      </query>
      <mapping>
          <setProperty></setProperty>
          <getProperty>rnum, cmo, mno, id, grade, content, rdate</getProperty>
      </mapping>
  </sql>
  <sql id="listCount">
      <query>
          <![CDATA[
            SELECT COUNT(*) AS total FROM comments WHERE mno = :mno
          ]]>
      </query>
      <mapping>
          <setProperty></setProperty>
          <getProperty>total</getProperty>
      </mapping>
  </sql>
  <sql id="listId">
      <query>
          <![CDATA[
             SELECT COUNT(*) AS cnt FROM comments WHERE id LIKE '${id}' AND mno LIKE :mno
          ]]>
      </query>
      <mapping>
          <setProperty></setProperty>
          <getProperty>cnt</getProperty>
      </mapping>
  </sql>
  <sql id="listReviewRight">
      <query>
          <![CDATA[
            SELECT DISTINCT TO_CHAR(theaterinfo.time, 'HH24:MI'), cdate
            FROM seat
            INNER JOIN theaterinfo ON seat.tino = theaterinfo.tino
            INNER JOIN payment ON seat.randomkey = payment.randomkey
            WHERE seat.id LIKE '${id}' AND mno LIKE :mno
          ]]>
      </query>
      <mapping>
          <setProperty></setProperty>
          <getProperty>theaterinfo.time, cdate</getProperty>
      </mapping>
  </sql>
  </processor-info>
  
  <input>
    <block name="InBlock_1">
        <field name="id" type="string" label="회원아이디"></field>
        <field name="mno" type="string" label="영화번호"></field>
        <field name="startRow" type="int" label="시작행"></field>
        <field name="size" type="int" label="게시글수"></field>
    </block>
  </input>
  
  <output>
    <block name="OutBlock_1">
      <field name="id" type="string" label="회원아이디"></field>
      <field name="mno" type="string" label="영화번호"></field>
      <field name="cmo" type="string" label=" 댓글번호"></field>
      <field name="grade" type="string" label="평점"></field>
      <field name="content" type="string" label="내용"></field>
      <field name="rdate" type="string" label="등록일"></field>
      <field name="total" type="int" label="검색수"></field>
      <field name="cnt" type="int" label="id검색수"></field>
      <field name="rnum" type="int" label="댓글번호"></field>
      <field name="theaterinfo.time" type="string" label="상영시간"></field>
      <field name="cdate" type="string" label="예매일"></field>
    </block>
  </output>  

</transaction>

=== soyoungkim9/cyberProject/ksy-movie/src/main/webapp/WEB-INF/coreframe/bld/samples/soap/GetGeoIP.xml
<?xml version="1.0" encoding="EUC-KR"?>
<transaction name="GetGeoIP" xmlns="http://www.cyber-i.com/xml/bld"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.cyber-i.com/xml/bld   http://www.cyber-i.com/xml/ns/bld-5.0.xsd">

	<info>
		<effective-date></effective-date>
		<description>IP 주소로 위치를 알아보는 WebService 예제</description>
		<version>0.2</version>
		<name>WebServiecs 예제</name>
		<status>confirmation</status>
	</info>
	
  <processor-info type="soap">
    <property name="xmlns:xsd" value="http://www.w3.org/1999/XMLSchema"/>
    <property name="xmlns:xsi" value="http://www.w3.org/1999/XMLSchema-instance"/>
    <property name="xmlns:q0" value="http://www.webservicex.net/"></property>
    <property name="soap.url" value= "http://www.webservicex.net/geoipservice.asmx"/>
    <property name="soap.action" value="http://www.webservicex.net/GetGeoIP"/>
    <property name="soap.output" value="DataSet"/>
  </processor-info>
  
  
  <input>
    <block name="arg" repeat="1">
      <field default="222.122.195.5" name="IPAddress" type="string" xpath="/q0:GetGeoIP/q0:IPAddress"/>
    </block>
    
    <xml-document>
      <q0:GetGeoIP xmlns:q0="http://www.webservicex.net/">
        <q0:IPAddress></q0:IPAddress>
      </q0:GetGeoIP>
    </xml-document>
    
  </input>
  <output>
    <block id="result" name="Address_Data" repeat="1" xpath="//q0:GetGeoIPResponse/q0:GetGeoIPResult">
      <field name="ReturnCode" type="int" xpath="q0:ReturnCode"></field>
      <field name="IP" type="string" xpath="q0:IP"></field>
      <field name="ReturnCodeDetails" type="string" xpath="q0:ReturnCodeDetails"></field>
      <field name="CountryName" type="string" xpath="q0:CountryName"></field>
      <field name="CountryCode" type="string" xpath="q0:CountryCode"></field>
    </block>
  </output>
</transaction>
